# Generated by Django 5.0.6 on 2024-05-22 20:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('fullname', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='Please enter a valid Iranian phone number.', regex='^(?:(?:\\+|00)98|0)?9\\d{9}$')])),
                ('password', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='Passwords must be at least 8 characters long and contain at least one digit, one lowercase letter, one uppercase letter, and one non-alphanumeric character.', regex='^(?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[^\\w\\s]).{8,}$')])),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
        ),
    ]
